"""Add PromptTemplate and DocumentTemplate tables

Revision ID: 3b72d8f21de6
Revises: 9aa3d131a822
Create Date: 2026-03-22 22:25:27.971777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b72d8f21de6'
down_revision: Union[str, None] = '9aa3d131a822'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
