"""Add fields to Card model: status, priority, order, assignee

Revision ID: 64ee08498e7e
Revises: 6f08941cf9f2
Create Date: 2026-03-21 22:47:45.042416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ee08498e7e'
down_revision: Union[str, None] = '6f08941cf9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('priority', sa.Enum('low', 'medium', 'high', name='cardpriority'), nullable=True))
    op.add_column('cards', sa.Column('order_index', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('cards', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('cards', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('cards', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'cards', 'users', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.alter_column('cards', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('cards', 'updated_at')
    op.drop_column('cards', 'created_at')
    op.drop_column('cards', 'due_date')
    op.drop_column('cards', 'assignee_id')
    op.drop_column('cards', 'order_index')
    op.drop_column('cards', 'priority')
    # ### end Alembic commands ###
