"""Add template tables

Revision ID: 9aa3d131a822
Revises: b6f3d52d7e48
Create Date: 2026-03-22 22:15:41.032673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aa3d131a822'
down_revision: Union[str, None] = 'b6f3d52d7e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('template_type', sa.Enum('prompt_meta_why', 'prompt_meta_requirements', 'prompt_meta_stakeholders', 'prompt_card_description', 'prompt_card_subtasks', 'prompt_summary', 'doc_project_brief', 'doc_requirements', 'doc_status_report', 'doc_retrospective', name='templatetype'), nullable=False),
    sa.Column('content_template', sa.Text(), nullable=False),
    sa.Column('output_format', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_type')
    )
    op.create_index(op.f('ix_document_templates_id'), 'document_templates', ['id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('template_type', sa.Enum('prompt_meta_why', 'prompt_meta_requirements', 'prompt_meta_stakeholders', 'prompt_card_description', 'prompt_card_subtasks', 'prompt_summary', 'doc_project_brief', 'doc_requirements', 'doc_status_report', 'doc_retrospective', name='templatetype'), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('default_model', sa.String(), nullable=True),
    sa.Column('default_temperature', sa.Integer(), nullable=True),
    sa.Column('default_max_tokens', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_type')
    )
    op.create_index(op.f('ix_prompt_templates_id'), 'prompt_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_templates_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_document_templates_id'), table_name='document_templates')
    op.drop_table('document_templates')
    # ### end Alembic commands ###
